spring.application.name=ffs

spring.datasource.url=jdbc:postgresql://localhost:5432/finale
spring.datasource.username=postgres
spring.datasource.password=pfepfe
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration pour Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


app.client.url=http://localhost:4200/login


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=meznedharoun99@gmail.com
spring.mail.password=bawc omzl ikyj kjgy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true